project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Data Driven Examination of baseball Performance Metrics"
  author:
    - Alan Wong (agw2252)
    - Srishaan Iyengar (si2465)
  repo-url: https://github.com/Srishaan/Baseball
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


