# Data

## Description

For this project, there are four key data sources that will be utilized. 

The first two datasets are obtained using the [`pybaseball`](https://github.com/jldbc/pybaseball) package, a Python library (last updated on September 8, 2023 with updates every 1-2 months on average) that is provides access to various reputable baseball sources such as [FanGraphs](https://www.fangraphs.com/) and [Baseball Reference](https://www.baseball-reference.com/). By utilizing `pybaseball`'s implemented `batting_stats()` and `pitching_stats()` functions, we get the batting data and pitching statistics for MLB players, saved as "batting_stats.csv" and "pitching_stats.csv", respectively. The batting statistics dataset has dimensions of 10,665 × 319, and the pitching statistics dataset has the dimensions of 6,423 × 392.

The last two datasets are sourced from [`BaseballR`](https://billpetti.github.io/baseballr/) package, an R library (last updated on January 16, 2024 with updates every 2-3 months on average) designed for accessing and analyzing baseball data from other reputable sources such as Statcast (an analytics system used by the MLB to track baseball data) and [Baseball Savant](https://baseballsavant.mlb.com/). Using the `BaseballR` package, we retrieve baseball draft data for each year from 1965 to 2023, which includes details about player drafts such as team, round, and selection year, saved as "draft_df.csv". Additionally, we run the `chadwick_player_lu()` function from `BaseballR` to get a database of player biographical and career information from the Chadwick Baseball Bureau, which we save as "chadwick_data.csv". The draft dataset has dimensions of 67903 x 84 and the Chadwick player dataset has dimensions of 512843 x 40.

A description of the issues/problems with the data will be provided in the missing value analysis section below.

## Missing value analysis

```{r}
library(tidyverse)

chadwick_data <- read_csv("chadwick_data.csv")

chadwick_data_uniform <- chadwick_data %>%
  mutate(across(everything(), as.character))

missing_chadwick <- chadwick_data_uniform %>%
  mutate(row_id = row_number()) %>%
  pivot_longer(-row_id, names_to = "variable", values_to = "value") %>%
  mutate(missing = is.na(value))

ggplot(missing_chadwick, aes(x = variable, y = row_id, fill = missing)) +
  geom_tile() +
  scale_fill_manual(values = c("FALSE" = "white", "TRUE" = "red"), name = "Missing") +
  theme_minimal() +
  labs(
    title = "Heatmap of Missing Values in Chadwick Data",
    x = "Variables",
    y = "Rows"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_blank()
  )
```